### ISSUE TITLE
local variable 'img_tr' referenced before assignment in data_oh.py and data_vlcs.py

### ISSUE THREAD

**Issue by abse4411** [hikvision-research/DomainGeneralization#1]
**In data/data_oh.py (line 108), local variable 'img_tr'  referenced before assignment**
`
def single_train_dataloader(args, patches=False):
    val_datasets = []
    val_datasets.append(ImageFolder_new(os.path.join(args.root, args.target, 'train/'), transform=img_tr))
    img_tr = get_train_transformers(args)
`
It also happens in  data/data_vlcs.py (line 107)
`
def single_train_dataloader(args, patches=False):
    val_datasets = []
    val_datasets.append(ImageFolder_new(os.path.join(args.root, args.target, 'train/'), transform=img_tr))
    img_tr = get_train_transformers(args)
`
Plz fix it, thanks.

**Comment by abse4411** [comment]
variable 'names' and 'labels' is not defined in these files:
`def single_train_dataloader(args, patches=False):
    val_datasets = []
    img_tr = get_train_transformers(args)
    val_datasets.append(ImageFolder_new(os.path.join(args.root, args.target, 'train/'), transform=img_tr))
    val_dataset = TestNewDataset(args.root, names, labels, img_transformer=img_tr)`

**Comment by lockonlee** [comment]
> **In data/data_oh.py (line 108), local variable 'img_tr' referenced before assignment** `def single_train_dataloader(args, patches=False): val_datasets = [] val_datasets.append(ImageFolder_new(os.path.join(args.root, args.target, 'train/'), transform=img_tr)) img_tr = get_train_transformers(args)` It also happens in data/data_vlcs.py (line 107) `def single_train_dataloader(args, patches=False): val_datasets = [] val_datasets.append(ImageFolder_new(os.path.join(args.root, args.target, 'train/'), transform=img_tr)) img_tr = get_train_transformers(args)` Plz fix it, thanks.

Thanks for the reminder, we have fixed this bug

**Comment by lockonlee** [comment]
> **In data/data_oh.py (line 108), local variable 'img_tr' referenced before assignment** `def single_train_dataloader(args, patches=False): val_datasets = [] val_datasets.append(ImageFolder_new(os.path.join(args.root, args.target, 'train/'), transform=img_tr)) img_tr = get_train_transformers(args)` It also happens in data/data_vlcs.py (line 107) `def single_train_dataloader(args, patches=False): val_datasets = [] val_datasets.append(ImageFolder_new(os.path.join(args.root, args.target, 'train/'), transform=img_tr)) img_tr = get_train_transformers(args)` Plz fix it, thanks.

Thanks for your reminder, we have fixed this bug.
